function modelPath = build_stage5b_model()
%BUILD_STAGE5B_MODEL Create the Stage 5B PI anti-windup Simulink model.

projectRoot = fileparts(fileparts(mfilename("fullpath")));
modelDirectory = fullfile(projectRoot, "matlab");
modelName = "stage5b_pi_anti_windup";
modelPath = fullfile(modelDirectory, modelName + ".slx");

if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
if isfile(modelPath)
    delete(modelPath);
end

new_system(modelName);
set_param(modelName, ...
    "Solver", "FixedStepDiscrete", ...
    "FixedStep", "10", ...
    "StopTime", "3600", ...
    "ReturnWorkspaceOutputs", "on");

% PI controller and conditional-integration anti-windup logic.
add_block("simulink/Sources/Constant", modelName + "/CHWS Setpoint", ...
    "Value", "7.0", "Position", [80 70 160 100]);
add_block("simulink/Math Operations/Sum", modelName + "/Temperature Error", ...
    "Inputs", "+-", "Position", [270 125 295 175]);
add_block("simulink/Math Operations/Gain", modelName + "/Kp", ...
    "Gain", "0.3", "Position", [365 130 435 170]);
add_block("simulink/Discrete/Unit Delay", modelName + "/Integral State", ...
    "InitialCondition", "300", "SampleTime", "10", ...
    "Position", [300 300 380 340]);
add_block("simulink/Math Operations/Gain", modelName + "/Ki", ...
    "Gain", "0.001", "Position", [460 315 530 355]);
add_block("simulink/Math Operations/Gain", modelName + "/Error x dt", ...
    "Gain", "10", "Position", [300 430 380 470]);
add_block("simulink/Math Operations/Sum", modelName + "/Candidate Integral", ...
    "Inputs", "++", "Position", [480 415 505 475]);
add_block("simulink/Math Operations/Sum", modelName + "/PI Sum", ...
    "Inputs", "++", "Position", [690 125 715 180]);
add_block("simulink/Discontinuities/Saturation", modelName + "/Cooling Limit", ...
    "LowerLimit", "0", "UpperLimit", "1", ...
    "Position", [800 120 880 190]);
add_block("simulink/Math Operations/Gain", modelName + "/Maximum Cooling", ...
    "Gain", "100", "Position", [1000 130 1080 180]);

add_block("simulink/Sources/Constant", modelName + "/Upper Limit", ...
    "Value", "1", "Position", [560 380 600 410]);
add_block("simulink/Logic and Bit Operations/Relational Operator", ...
    modelName + "/Command High", "Operator", ">=", ...
    "Position", [650 365 695 410]);
add_block("simulink/Sources/Constant", modelName + "/Zero Positive", ...
    "Value", "0", "Position", [560 435 600 465]);
add_block("simulink/Logic and Bit Operations/Relational Operator", ...
    modelName + "/Error Positive", "Operator", ">", ...
    "Position", [650 420 695 465]);
add_block("simulink/Logic and Bit Operations/Logical Operator", ...
    modelName + "/High Saturation Hold", "Operator", "AND", "Inputs", "2", ...
    "Position", [755 390 800 435]);

add_block("simulink/Sources/Constant", modelName + "/Lower Limit", ...
    "Value", "0", "Position", [560 535 600 565]);
add_block("simulink/Logic and Bit Operations/Relational Operator", ...
    modelName + "/Command Low", "Operator", "<=", ...
    "Position", [650 520 695 565]);
add_block("simulink/Sources/Constant", modelName + "/Zero Negative", ...
    "Value", "0", "Position", [560 590 600 620]);
add_block("simulink/Logic and Bit Operations/Relational Operator", ...
    modelName + "/Error Negative", "Operator", "<", ...
    "Position", [650 575 695 620]);
add_block("simulink/Logic and Bit Operations/Logical Operator", ...
    modelName + "/Low Saturation Hold", "Operator", "AND", "Inputs", "2", ...
    "Position", [755 545 800 590]);
add_block("simulink/Logic and Bit Operations/Logical Operator", ...
    modelName + "/Hold Integral", "Operator", "OR", "Inputs", "2", ...
    "Position", [845 470 890 520]);
add_block("simulink/Signal Routing/Switch", modelName + "/Integral Update Switch", ...
    "Threshold", "0.5", "Position", [940 420 990 585]);

% Two-node chilled-water plant retained from Stage 3.
add_block("simulink/Discrete/Unit Delay", modelName + "/CHWS State", ...
    "InitialCondition", "7.0", "SampleTime", "10", ...
    "Position", [80 235 160 275]);
add_block("simulink/Discrete/Unit Delay", modelName + "/CHWR State", ...
    "InitialCondition", "8.435406698564593", "SampleTime", "10", ...
    "Position", [80 800 160 840]);
add_block("simulink/Math Operations/Sum", modelName + "/Return minus Supply", ...
    "Inputs", "+-", "Position", [300 680 325 730]);
add_block("simulink/Math Operations/Gain", modelName + "/Flow Heat Transfer", ...
    "Gain", "5.0*4.18", "Position", [400 685 500 725]);

% A 30 kW base load plus a +90 kW step and a -90 kW recovery step.
add_block("simulink/Sources/Step", modelName + "/Overload Step", ...
    "Time", "600", "Before", "30", "After", "120", "SampleTime", "10", ...
    "Position", [80 950 165 990]);
add_block("simulink/Sources/Step", modelName + "/Recovery Step", ...
    "Time", "1200", "Before", "0", "After", "-90", "SampleTime", "10", ...
    "Position", [80 1015 165 1055]);
add_block("simulink/Math Operations/Sum", modelName + "/Building Load", ...
    "Inputs", "++", "Position", [300 965 325 1025]);

add_block("simulink/Math Operations/Sum", modelName + "/Supply Net Heat", ...
    "Inputs", "+-", "Position", [1100 680 1125 730]);
add_block("simulink/Math Operations/Gain", modelName + "/Supply Temperature Change", ...
    "Gain", "10/(500*4.18)", "Position", [1200 685 1320 725]);
add_block("simulink/Math Operations/Sum", modelName + "/Next CHWS", ...
    "Inputs", "++", "Position", [1400 630 1425 680]);

add_block("simulink/Math Operations/Sum", modelName + "/Return Net Heat", ...
    "Inputs", "+-", "Position", [650 810 675 860]);
add_block("simulink/Math Operations/Gain", modelName + "/Return Temperature Change", ...
    "Gain", "10/(500*4.18)", "Position", [750 815 870 855]);
add_block("simulink/Math Operations/Sum", modelName + "/Next CHWR", ...
    "Inputs", "++", "Position", [990 760 1015 810]);

% Logged signals used for sample-by-sample Python comparison.
add_block("simulink/Sinks/To Workspace", modelName + "/Log CHWS", ...
    "VariableName", "sim_supply", "SaveFormat", "Timeseries", ...
    "Position", [1490 635 1600 665]);
add_block("simulink/Sinks/To Workspace", modelName + "/Log CHWR", ...
    "VariableName", "sim_return", "SaveFormat", "Timeseries", ...
    "Position", [1090 765 1200 795]);
add_block("simulink/Sinks/To Workspace", modelName + "/Log Cooling Fraction", ...
    "VariableName", "sim_cooling_fraction", "SaveFormat", "Timeseries", ...
    "Position", [1000 70 1150 100]);
add_block("simulink/Sinks/To Workspace", modelName + "/Log Integral State", ...
    "VariableName", "sim_integral_state", "SaveFormat", "Timeseries", ...
    "Position", [440 260 580 290]);
add_block("simulink/Sinks/To Workspace", modelName + "/Log Load", ...
    "VariableName", "sim_load", "SaveFormat", "Timeseries", ...
    "Position", [400 970 500 1000]);
add_block("simulink/Sinks/To Workspace", modelName + "/Log Flow Heat", ...
    "VariableName", "sim_flow_heat", "SaveFormat", "Timeseries", ...
    "Position", [560 675 680 705]);

% Controller signal path.
add_line(modelName, "CHWS State/1", "Temperature Error/1", "autorouting", "on");
add_line(modelName, "CHWS Setpoint/1", "Temperature Error/2", "autorouting", "on");
add_line(modelName, "Temperature Error/1", "Kp/1");
add_line(modelName, "Temperature Error/1", "Error x dt/1", "autorouting", "on");
add_line(modelName, "Integral State/1", "Ki/1");
add_line(modelName, "Integral State/1", "Candidate Integral/1", "autorouting", "on");
add_line(modelName, "Integral State/1", "Integral Update Switch/1", "autorouting", "on");
add_line(modelName, "Integral State/1", "Log Integral State/1", "autorouting", "on");
add_line(modelName, "Error x dt/1", "Candidate Integral/2");
add_line(modelName, "Kp/1", "PI Sum/1", "autorouting", "on");
add_line(modelName, "Ki/1", "PI Sum/2", "autorouting", "on");
add_line(modelName, "PI Sum/1", "Cooling Limit/1");
add_line(modelName, "Cooling Limit/1", "Maximum Cooling/1");
add_line(modelName, "Cooling Limit/1", "Log Cooling Fraction/1", "autorouting", "on");

% Hold when saturated high with positive error or low with negative error.
add_line(modelName, "PI Sum/1", "Command High/1", "autorouting", "on");
add_line(modelName, "Upper Limit/1", "Command High/2");
add_line(modelName, "Temperature Error/1", "Error Positive/1", "autorouting", "on");
add_line(modelName, "Zero Positive/1", "Error Positive/2");
add_line(modelName, "Command High/1", "High Saturation Hold/1");
add_line(modelName, "Error Positive/1", "High Saturation Hold/2");
add_line(modelName, "PI Sum/1", "Command Low/1", "autorouting", "on");
add_line(modelName, "Lower Limit/1", "Command Low/2");
add_line(modelName, "Temperature Error/1", "Error Negative/1", "autorouting", "on");
add_line(modelName, "Zero Negative/1", "Error Negative/2");
add_line(modelName, "Command Low/1", "Low Saturation Hold/1");
add_line(modelName, "Error Negative/1", "Low Saturation Hold/2");
add_line(modelName, "High Saturation Hold/1", "Hold Integral/1", "autorouting", "on");
add_line(modelName, "Low Saturation Hold/1", "Hold Integral/2", "autorouting", "on");
add_line(modelName, "Hold Integral/1", "Integral Update Switch/2", "autorouting", "on");
add_line(modelName, "Candidate Integral/1", "Integral Update Switch/3", "autorouting", "on");
add_line(modelName, "Integral Update Switch/1", "Integral State/1", "autorouting", "on");

% Supply and return energy balances.
add_line(modelName, "CHWR State/1", "Return minus Supply/1", "autorouting", "on");
add_line(modelName, "CHWS State/1", "Return minus Supply/2", "autorouting", "on");
add_line(modelName, "Return minus Supply/1", "Flow Heat Transfer/1");
add_line(modelName, "Flow Heat Transfer/1", "Supply Net Heat/1", "autorouting", "on");
add_line(modelName, "Flow Heat Transfer/1", "Return Net Heat/2", "autorouting", "on");
add_line(modelName, "Flow Heat Transfer/1", "Log Flow Heat/1", "autorouting", "on");
add_line(modelName, "Maximum Cooling/1", "Supply Net Heat/2", "autorouting", "on");
add_line(modelName, "Supply Net Heat/1", "Supply Temperature Change/1");
add_line(modelName, "Supply Temperature Change/1", "Next CHWS/2", "autorouting", "on");
add_line(modelName, "CHWS State/1", "Next CHWS/1", "autorouting", "on");
add_line(modelName, "Next CHWS/1", "CHWS State/1", "autorouting", "on");
add_line(modelName, "CHWS State/1", "Log CHWS/1", "autorouting", "on");

add_line(modelName, "Overload Step/1", "Building Load/1");
add_line(modelName, "Recovery Step/1", "Building Load/2");
add_line(modelName, "Building Load/1", "Return Net Heat/1", "autorouting", "on");
add_line(modelName, "Building Load/1", "Log Load/1", "autorouting", "on");
add_line(modelName, "Return Net Heat/1", "Return Temperature Change/1");
add_line(modelName, "Return Temperature Change/1", "Next CHWR/2", "autorouting", "on");
add_line(modelName, "CHWR State/1", "Next CHWR/1", "autorouting", "on");
add_line(modelName, "Next CHWR/1", "CHWR State/1", "autorouting", "on");
add_line(modelName, "CHWR State/1", "Log CHWR/1", "autorouting", "on");

annotationText = sprintf( ...
    "Stage 5B: exercised PI anti-windup cross-validation\nHold I when (u >= 1 and e > 0) or (u <= 0 and e < 0) | 120 kW overload, 100 kW limit");
annotation = Simulink.Annotation(modelName, annotationText);
annotation.Position = [430 10 1170 60];
annotation.FontSize = 12;

set_param(modelName + "/CHWS State", "BackgroundColor", "lightBlue");
set_param(modelName + "/CHWR State", "BackgroundColor", "orange");
set_param(modelName + "/Integral State", "BackgroundColor", "lightBlue");
set_param(modelName + "/Overload Step", "BackgroundColor", "yellow");
set_param(modelName + "/Recovery Step", "BackgroundColor", "yellow");

save_system(modelName, modelPath);
close_system(modelName, 0);
fprintf("Created Simulink model: %s\n", modelPath);
end
