function modelPath = build_stage5b_model()
%BUILD_STAGE5B_MODEL Create the Stage 5B PI anti-windup Simulink model.

projectRoot = fileparts(fileparts(mfilename("fullpath")));
modelDirectory = fullfile(projectRoot, "matlab");
modelName = "stage5b_pi_anti_windup";
modelPath = fullfile(modelDirectory, modelName + ".slx");

if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
if isfile(modelPath)
    delete(modelPath);
end

new_system(modelName);
set_param(modelName, ...
    "Solver", "FixedStepDiscrete", ...
    "FixedStep", "10", ...
    "StopTime", "3600", ...
    "ReturnWorkspaceOutputs", "on");

% PI controller and conditional-integration anti-windup logic.
add_block("simulink/Sources/Constant", modelName + "/CHWS Setpoint", ...
    "Value", "7.0", "Position", [70 45 140 75]);
add_block("simulink/Math Operations/Sum", modelName + "/Temperature Error", ...
    "Inputs", "+-", "Position", [205 105 230 150]);
add_block("simulink/Math Operations/Gain", modelName + "/Kp", ...
    "Gain", "0.3", "Position", [285 105 355 145]);
add_block("simulink/Discrete/Unit Delay", modelName + "/Integral State", ...
    "InitialCondition", "300", "SampleTime", "10", ...
    "Position", [280 230 350 270]);
add_block("simulink/Math Operations/Gain", modelName + "/Ki", ...
    "Gain", "0.001", "Position", [415 230 485 270]);
add_block("simulink/Math Operations/Gain", modelName + "/Error x dt", ...
    "Gain", "10", "Position", [280 330 350 370]);
add_block("simulink/Math Operations/Sum", modelName + "/Candidate Integral", ...
    "Inputs", "++", "Position", [425 320 450 375]);
add_block("simulink/Math Operations/Sum", modelName + "/PI Sum", ...
    "Inputs", "++", "Position", [545 130 570 185]);
add_block("simulink/Discontinuities/Saturation", modelName + "/Cooling Limit", ...
    "LowerLimit", "0", "UpperLimit", "1", ...
    "Position", [635 130 705 190]);
add_block("simulink/Math Operations/Gain", modelName + "/Maximum Cooling", ...
    "Gain", "100", "Position", [775 140 855 185]);

add_block("simulink/Sources/Constant", modelName + "/Upper Limit", ...
    "Value", "1", "Position", [540 285 575 315]);
add_block("simulink/Logic and Bit Operations/Relational Operator", ...
    modelName + "/Command High", "Operator", ">=", ...
    "Position", [625 270 665 315]);
add_block("simulink/Sources/Constant", modelName + "/Zero Positive", ...
    "Value", "0", "Position", [540 335 575 365]);
add_block("simulink/Logic and Bit Operations/Relational Operator", ...
    modelName + "/Error Positive", "Operator", ">", ...
    "Position", [625 325 665 370]);
add_block("simulink/Logic and Bit Operations/Logical Operator", ...
    modelName + "/High Saturation Hold", "Operator", "AND", "Inputs", "2", ...
    "Position", [725 290 765 335]);

add_block("simulink/Sources/Constant", modelName + "/Lower Limit", ...
    "Value", "0", "Position", [540 410 575 440]);
add_block("simulink/Logic and Bit Operations/Relational Operator", ...
    modelName + "/Command Low", "Operator", "<=", ...
    "Position", [625 395 665 440]);
add_block("simulink/Sources/Constant", modelName + "/Zero Negative", ...
    "Value", "0", "Position", [540 460 575 490]);
add_block("simulink/Logic and Bit Operations/Relational Operator", ...
    modelName + "/Error Negative", "Operator", "<", ...
    "Position", [625 450 665 495]);
add_block("simulink/Logic and Bit Operations/Logical Operator", ...
    modelName + "/Low Saturation Hold", "Operator", "AND", "Inputs", "2", ...
    "Position", [725 415 765 460]);
add_block("simulink/Logic and Bit Operations/Logical Operator", ...
    modelName + "/Hold Integral", "Operator", "OR", "Inputs", "2", ...
    "Position", [830 350 870 400]);
add_block("simulink/Signal Routing/Switch", modelName + "/Integral Update Switch", ...
    "Threshold", "0.5", "Position", [940 315 985 410]);

% Two-node chilled-water plant retained from Stage 3.
add_block("simulink/Discrete/Unit Delay", modelName + "/CHWS State", ...
    "InitialCondition", "7.0", "SampleTime", "10", ...
    "Position", [70 180 140 220]);
add_block("simulink/Discrete/Unit Delay", modelName + "/CHWR State", ...
    "InitialCondition", "8.435406698564593", "SampleTime", "10", ...
    "Position", [70 600 140 640]);
add_block("simulink/Math Operations/Sum", modelName + "/Return minus Supply", ...
    "Inputs", "+-", "Position", [255 510 280 560]);
add_block("simulink/Math Operations/Gain", modelName + "/Flow Heat Transfer", ...
    "Gain", "5.0*4.18", "Position", [340 510 435 560]);

% A 30 kW base load plus a +90 kW step and a -90 kW recovery step.
add_block("simulink/Sources/Step", modelName + "/Overload Step", ...
    "Time", "600", "Before", "30", "After", "120", "SampleTime", "10", ...
    "Position", [70 770 155 810]);
add_block("simulink/Sources/Step", modelName + "/Recovery Step", ...
    "Time", "1200", "Before", "0", "After", "-90", "SampleTime", "10", ...
    "Position", [70 835 155 875]);
add_block("simulink/Math Operations/Sum", modelName + "/Building Load", ...
    "Inputs", "++", "Position", [220 790 245 850]);

add_block("simulink/Math Operations/Sum", modelName + "/Supply Net Heat", ...
    "Inputs", "+-", "Position", [730 545 755 595]);
add_block("simulink/Math Operations/Gain", modelName + "/Supply Temperature Change", ...
    "Gain", "10/(500*4.18)", "Position", [815 545 925 595]);
add_block("simulink/Math Operations/Sum", modelName + "/Next CHWS", ...
    "Inputs", "++", "Position", [1005 500 1030 550]);

add_block("simulink/Math Operations/Sum", modelName + "/Return Net Heat", ...
    "Inputs", "+-", "Position", [515 665 540 715]);
add_block("simulink/Math Operations/Gain", modelName + "/Return Temperature Change", ...
    "Gain", "10/(500*4.18)", "Position", [605 665 715 715]);
add_block("simulink/Math Operations/Sum", modelName + "/Next CHWR", ...
    "Inputs", "++", "Position", [795 610 820 660]);

% Logged signals used for sample-by-sample Python comparison.
add_block("simulink/Sinks/To Workspace", modelName + "/Log CHWS", ...
    "VariableName", "sim_supply", "SaveFormat", "Timeseries", ...
    "Position", [1100 500 1200 530]);
add_block("simulink/Sinks/To Workspace", modelName + "/Log CHWR", ...
    "VariableName", "sim_return", "SaveFormat", "Timeseries", ...
    "Position", [895 610 995 640]);
add_block("simulink/Sinks/To Workspace", modelName + "/Log Cooling Fraction", ...
    "VariableName", "sim_cooling_fraction", "SaveFormat", "Timeseries", ...
    "Position", [775 70 915 100]);
add_block("simulink/Sinks/To Workspace", modelName + "/Log Integral State", ...
    "VariableName", "sim_integral_state", "SaveFormat", "Timeseries", ...
    "Position", [410 200 540 230]);
add_block("simulink/Sinks/To Workspace", modelName + "/Log Load", ...
    "VariableName", "sim_load", "SaveFormat", "Timeseries", ...
    "Position", [310 790 405 820]);
add_block("simulink/Sinks/To Workspace", modelName + "/Log Flow Heat", ...
    "VariableName", "sim_flow_heat", "SaveFormat", "Timeseries", ...
    "Position", [480 520 580 550]);

% Controller signal path.
add_line(modelName, "CHWS State/1", "Temperature Error/1", "autorouting", "on");
add_line(modelName, "CHWS Setpoint/1", "Temperature Error/2", "autorouting", "on");
add_line(modelName, "Temperature Error/1", "Kp/1");
add_line(modelName, "Temperature Error/1", "Error x dt/1", "autorouting", "on");
add_line(modelName, "Integral State/1", "Ki/1");
add_line(modelName, "Integral State/1", "Candidate Integral/1", "autorouting", "on");
add_line(modelName, "Integral State/1", "Integral Update Switch/1", "autorouting", "on");
add_line(modelName, "Integral State/1", "Log Integral State/1", "autorouting", "on");
add_line(modelName, "Error x dt/1", "Candidate Integral/2");
add_line(modelName, "Kp/1", "PI Sum/1", "autorouting", "on");
add_line(modelName, "Ki/1", "PI Sum/2", "autorouting", "on");
add_line(modelName, "PI Sum/1", "Cooling Limit/1");
add_line(modelName, "Cooling Limit/1", "Maximum Cooling/1");
add_line(modelName, "Cooling Limit/1", "Log Cooling Fraction/1", "autorouting", "on");

% Hold when saturated high with positive error or low with negative error.
add_line(modelName, "PI Sum/1", "Command High/1", "autorouting", "on");
add_line(modelName, "Upper Limit/1", "Command High/2");
add_line(modelName, "Temperature Error/1", "Error Positive/1", "autorouting", "on");
add_line(modelName, "Zero Positive/1", "Error Positive/2");
add_line(modelName, "Command High/1", "High Saturation Hold/1");
add_line(modelName, "Error Positive/1", "High Saturation Hold/2");
add_line(modelName, "PI Sum/1", "Command Low/1", "autorouting", "on");
add_line(modelName, "Lower Limit/1", "Command Low/2");
add_line(modelName, "Temperature Error/1", "Error Negative/1", "autorouting", "on");
add_line(modelName, "Zero Negative/1", "Error Negative/2");
add_line(modelName, "Command Low/1", "Low Saturation Hold/1");
add_line(modelName, "Error Negative/1", "Low Saturation Hold/2");
add_line(modelName, "High Saturation Hold/1", "Hold Integral/1", "autorouting", "on");
add_line(modelName, "Low Saturation Hold/1", "Hold Integral/2", "autorouting", "on");
add_line(modelName, "Hold Integral/1", "Integral Update Switch/2", "autorouting", "on");
add_line(modelName, "Candidate Integral/1", "Integral Update Switch/3", "autorouting", "on");
add_line(modelName, "Integral Update Switch/1", "Integral State/1", "autorouting", "on");

% Supply and return energy balances.
add_line(modelName, "CHWR State/1", "Return minus Supply/1", "autorouting", "on");
add_line(modelName, "CHWS State/1", "Return minus Supply/2", "autorouting", "on");
add_line(modelName, "Return minus Supply/1", "Flow Heat Transfer/1");
add_line(modelName, "Flow Heat Transfer/1", "Supply Net Heat/1", "autorouting", "on");
add_line(modelName, "Flow Heat Transfer/1", "Return Net Heat/2", "autorouting", "on");
add_line(modelName, "Flow Heat Transfer/1", "Log Flow Heat/1", "autorouting", "on");
add_line(modelName, "Maximum Cooling/1", "Supply Net Heat/2", "autorouting", "on");
add_line(modelName, "Supply Net Heat/1", "Supply Temperature Change/1");
add_line(modelName, "Supply Temperature Change/1", "Next CHWS/2", "autorouting", "on");
add_line(modelName, "CHWS State/1", "Next CHWS/1", "autorouting", "on");
add_line(modelName, "Next CHWS/1", "CHWS State/1", "autorouting", "on");
add_line(modelName, "CHWS State/1", "Log CHWS/1", "autorouting", "on");

add_line(modelName, "Overload Step/1", "Building Load/1");
add_line(modelName, "Recovery Step/1", "Building Load/2");
add_line(modelName, "Building Load/1", "Return Net Heat/1", "autorouting", "on");
add_line(modelName, "Building Load/1", "Log Load/1", "autorouting", "on");
add_line(modelName, "Return Net Heat/1", "Return Temperature Change/1");
add_line(modelName, "Return Temperature Change/1", "Next CHWR/2", "autorouting", "on");
add_line(modelName, "CHWR State/1", "Next CHWR/1", "autorouting", "on");
add_line(modelName, "Next CHWR/1", "CHWR State/1", "autorouting", "on");
add_line(modelName, "CHWR State/1", "Log CHWR/1", "autorouting", "on");

annotationText = sprintf( ...
    "Stage 5B: exercised PI anti-windup cross-validation\nHold I when (u >= 1 and e > 0) or (u <= 0 and e < 0) | 120 kW overload, 100 kW limit");
annotation = Simulink.Annotation(modelName, annotationText);
annotation.Position = [330 10 1030 60];
annotation.FontSize = 12;

set_param(modelName + "/CHWS State", "BackgroundColor", "lightBlue");
set_param(modelName + "/CHWR State", "BackgroundColor", "orange");
set_param(modelName + "/Integral State", "BackgroundColor", "lightBlue");
set_param(modelName + "/Overload Step", "BackgroundColor", "yellow");
set_param(modelName + "/Recovery Step", "BackgroundColor", "yellow");

save_system(modelName, modelPath);
close_system(modelName, 0);
fprintf("Created Simulink model: %s\n", modelPath);
end
