function summary = run_stage5b_validation()
%RUN_STAGE5B_VALIDATION Compare exercised anti-windup in Simulink and Python.

projectRoot = fileparts(fileparts(mfilename("fullpath")));
matlabDirectory = fullfile(projectRoot, "matlab");
modelName = "stage5b_pi_anti_windup";
modelPath = fullfile(matlabDirectory, modelName + ".slx");

addpath(matlabDirectory);
if ~isfile(modelPath)
    build_stage5b_model();
end

load_system(modelPath);
simulationOutput = sim(modelName, "ReturnWorkspaceOutputs", "on");
close_system(modelName, 0);

supplySeries = simulationOutput.get("sim_supply");
returnSeries = simulationOutput.get("sim_return");
coolingSeries = simulationOutput.get("sim_cooling_fraction");
integralSeries = simulationOutput.get("sim_integral_state");

timeS = supplySeries.Time(:);
simulinkSupplyC = squeeze(supplySeries.Data);
simulinkReturnC = squeeze(returnSeries.Data);
simulinkCoolingFraction = squeeze(coolingSeries.Data);
simulinkIntegralStateCS = squeeze(integralSeries.Data);

pythonPath = fullfile(projectRoot, "results", "stage5.csv");
allPythonResults = readtable(pythonPath, "VariableNamingRule", "preserve");
pythonResults = allPythonResults( ...
    string(allPythonResults.controller) == "PI_ANTI_WINDUP", :);
pythonTimeS = pythonResults.time_s;
pythonSupplyC = pythonResults.supply_temperature_c;
pythonReturnC = pythonResults.return_temperature_c;
pythonCoolingFraction = pythonResults.applied_cooling_fraction;
pythonIntegralStateCS = pythonResults.integral_error_c_s;

assert(numel(timeS) == height(pythonResults), ...
    "Simulink and Python must produce the same number of anti-windup samples.");
assert(max(abs(timeS - pythonTimeS)) <= 1e-12, ...
    "Simulink and Python sample times do not match.");

supplyErrorC = simulinkSupplyC - pythonSupplyC;
returnErrorC = simulinkReturnC - pythonReturnC;
coolingFractionError = simulinkCoolingFraction - pythonCoolingFraction;
integralStateErrorCS = simulinkIntegralStateCS - pythonIntegralStateCS;

maximumSupplyErrorC = max(abs(supplyErrorC));
maximumReturnErrorC = max(abs(returnErrorC));
maximumCoolingFractionError = max(abs(coolingFractionError));
maximumIntegralStateErrorCS = max(abs(integralStateErrorCS));
acceptanceLimit = 1e-9;
passed = maximumSupplyErrorC <= acceptanceLimit ...
    && maximumReturnErrorC <= acceptanceLimit ...
    && maximumCoolingFractionError <= acceptanceLimit ...
    && maximumIntegralStateErrorCS <= acceptanceLimit;

assert(passed, ...
    "Python-Simulink anti-windup signal difference exceeded the acceptance limit.");

recoveryMask = timeS >= 1200;
releaseIndex = find( ...
    recoveryMask & simulinkCoolingFraction < 1 - 1e-12, 1, "first");
assert(~isempty(releaseIndex), ...
    "The Simulink controller did not leave high saturation after recovery.");
saturationReleaseTimeS = timeS(releaseIndex) - 1200;
recoveryUndershootC = max(0, 7 - min(simulinkSupplyC(recoveryMask)));

assert(abs(saturationReleaseTimeS - 160) <= 1e-12, ...
    "The Simulink saturation-release metric does not match Stage 5A.");
assert(abs(recoveryUndershootC - 0.6121944916501274) <= 1e-9, ...
    "The Simulink recovery-undershoot metric does not match Stage 5A.");

comparison = table( ...
    timeS, ...
    pythonSupplyC, ...
    simulinkSupplyC, ...
    supplyErrorC, ...
    pythonReturnC, ...
    simulinkReturnC, ...
    returnErrorC, ...
    pythonCoolingFraction, ...
    simulinkCoolingFraction, ...
    coolingFractionError, ...
    pythonIntegralStateCS, ...
    simulinkIntegralStateCS, ...
    integralStateErrorCS, ...
    'VariableNames', [ ...
        "time_s", ...
        "python_supply_temperature_c", ...
        "simulink_supply_temperature_c", ...
        "supply_error_c", ...
        "python_return_temperature_c", ...
        "simulink_return_temperature_c", ...
        "return_error_c", ...
        "python_cooling_fraction", ...
        "simulink_cooling_fraction", ...
        "cooling_fraction_error", ...
        "python_integral_state_c_s", ...
        "simulink_integral_state_c_s", ...
        "integral_state_error_c_s"]);

comparisonPath = fullfile(projectRoot, "results", "stage5b_comparison.csv");
writetable(comparison, comparisonPath);

figureHandle = figure("Visible", "off", "Color", "white", ...
    "Position", [100 100 1200 900]);
tiledlayout(2, 2, "TileSpacing", "compact", "Padding", "compact");

nexttile;
plot(timeS / 60, pythonSupplyC, "-", "LineWidth", 2.2, ...
    "Color", [0.09 0.41 0.67]);
hold on;
plot(timeS / 60, simulinkSupplyC, "o", "MarkerIndices", 1:18:numel(timeS), ...
    "MarkerSize", 4, "Color", [0.09 0.41 0.67]);
xline(10, "--", "Overload");
xline(20, "--", "Recovery");
yline(7, "--", "Setpoint");
grid on;
xlabel("Simulated time (minutes)");
ylabel("CHWS (deg C)");
title("Supply temperature");
legend("Python", "Simulink", "Location", "northeast");

nexttile;
plot(timeS / 60, pythonReturnC, "-", "LineWidth", 2.2, ...
    "Color", [0.90 0.49 0.13]);
hold on;
plot(timeS / 60, simulinkReturnC, "s", "MarkerIndices", 1:18:numel(timeS), ...
    "MarkerSize", 4, "Color", [0.90 0.49 0.13]);
xline(10, "--", "Overload");
xline(20, "--", "Recovery");
grid on;
xlabel("Simulated time (minutes)");
ylabel("CHWR (deg C)");
title("Return temperature");
legend("Python", "Simulink", "Location", "northeast");

nexttile;
plot(timeS / 60, pythonCoolingFraction * 100, "-", "LineWidth", 2.2, ...
    "Color", [0.10 0.51 0.35]);
hold on;
plot(timeS / 60, simulinkCoolingFraction * 100, "o", ...
    "MarkerIndices", 1:18:numel(timeS), "MarkerSize", 4, ...
    "Color", [0.10 0.51 0.35]);
xline(10, "--", "Overload");
xline(20, "--", "Recovery");
grid on;
xlabel("Simulated time (minutes)");
ylabel("Cooling command (%)");
title("Anti-windup PI cooling output");
legend("Python", "Simulink", "Location", "southeast");

nexttile;
plot(timeS / 60, pythonIntegralStateCS, "-", "LineWidth", 2.2, ...
    "Color", [0.49 0.23 0.93]);
hold on;
plot(timeS / 60, simulinkIntegralStateCS, "s", ...
    "MarkerIndices", 1:18:numel(timeS), "MarkerSize", 4, ...
    "Color", [0.49 0.23 0.93]);
xline(10, "--", "Overload");
xline(20, "--", "Recovery");
grid on;
xlabel("Simulated time (minutes)");
ylabel("Integral state (deg C s)");
title("Conditionally accumulated error");
legend("Python", "Simulink", "Location", "southeast");

sgtitle("Stage 5B Python-Simulink anti-windup cross-validation");
plotPath = fullfile(projectRoot, "docs", ...
    "stage5b-python-simulink-comparison.png");
exportgraphics(figureHandle, plotPath, "Resolution", 170);
close(figureHandle);

summary = table( ...
    numel(timeS), ...
    maximumSupplyErrorC, ...
    maximumReturnErrorC, ...
    maximumCoolingFractionError, ...
    maximumIntegralStateErrorCS, ...
    acceptanceLimit, ...
    passed, ...
    saturationReleaseTimeS, ...
    recoveryUndershootC, ...
    simulinkSupplyC(end), ...
    simulinkReturnC(end), ...
    simulinkCoolingFraction(end), ...
    'VariableNames', [ ...
        "samples_compared", ...
        "maximum_supply_error_c", ...
        "maximum_return_error_c", ...
        "maximum_cooling_fraction_error", ...
        "maximum_integral_state_error_c_s", ...
        "acceptance_limit", ...
        "passed", ...
        "saturation_release_time_s", ...
        "recovery_undershoot_c", ...
        "final_simulink_supply_c", ...
        "final_simulink_return_c", ...
        "final_simulink_cooling_fraction"]);

summaryPath = fullfile(projectRoot, "results", "stage5b_summary.csv");
writetable(summary, summaryPath);

fprintf("Stage 5B Python-Simulink anti-windup cross-validation\n");
fprintf("Samples compared: %d\n", numel(timeS));
fprintf("Maximum CHWS difference: %.3e deg C\n", maximumSupplyErrorC);
fprintf("Maximum CHWR difference: %.3e deg C\n", maximumReturnErrorC);
fprintf("Maximum cooling-fraction difference: %.3e\n", maximumCoolingFractionError);
fprintf("Maximum integral-state difference: %.3e deg C s\n", maximumIntegralStateErrorCS);
fprintf("Saturation release after recovery: %.0f s\n", saturationReleaseTimeS);
fprintf("Recovery undershoot: %.3f deg C\n", recoveryUndershootC);
fprintf("Acceptance limit: %.1e in each signal's native units\n", acceptanceLimit);
fprintf("Cross-validation: PASS\n");
fprintf("Saved: %s\n", comparisonPath);
fprintf("Saved: %s\n", summaryPath);
fprintf("Saved: %s\n", plotPath);
end
