function summary = run_stage3b_validation()
%RUN_STAGE3B_VALIDATION Compare Simulink and Python Stage 3 results.

projectRoot = fileparts(fileparts(mfilename("fullpath")));
matlabDirectory = fullfile(projectRoot, "matlab");
modelName = "stage3b_chilled_water";
modelPath = fullfile(matlabDirectory, modelName + ".slx");

addpath(matlabDirectory);
if ~isfile(modelPath)
    build_stage3b_model();
end

load_system(modelPath);
simulationOutput = sim(modelName, "ReturnWorkspaceOutputs", "on");
close_system(modelName, 0);

supplySeries = simulationOutput.get("sim_supply");
returnSeries = simulationOutput.get("sim_return");
loadSeries = simulationOutput.get("sim_load");
coolingSeries = simulationOutput.get("sim_cooling");
flowHeatSeries = simulationOutput.get("sim_flow_heat");

timeS = supplySeries.Time(:);
simulinkSupplyC = squeeze(supplySeries.Data);
simulinkReturnC = squeeze(returnSeries.Data);
simulinkLoadKw = squeeze(loadSeries.Data);
simulinkCoolingKw = squeeze(coolingSeries.Data);
simulinkFlowHeatKw = squeeze(flowHeatSeries.Data);

pythonPath = fullfile(projectRoot, "results", "stage3.csv");
pythonResults = readtable(pythonPath, "VariableNamingRule", "preserve");
pythonTimeS = pythonResults.time_s;
pythonSupplyC = pythonResults.supply_temperature_c;
pythonReturnC = pythonResults.return_temperature_c;

assert(numel(timeS) == height(pythonResults), ...
    "Simulink and Python must produce the same number of samples.");
assert(max(abs(timeS - pythonTimeS)) <= 1e-12, ...
    "Simulink and Python sample times do not match.");

supplyErrorC = simulinkSupplyC - pythonSupplyC;
returnErrorC = simulinkReturnC - pythonReturnC;
maximumSupplyErrorC = max(abs(supplyErrorC));
maximumReturnErrorC = max(abs(returnErrorC));
acceptanceLimitC = 1e-9;
passed = maximumSupplyErrorC <= acceptanceLimitC ...
    && maximumReturnErrorC <= acceptanceLimitC;

assert(passed, ...
    "Python-Simulink temperature difference exceeded the acceptance limit.");

comparison = table( ...
    timeS, ...
    pythonSupplyC, ...
    simulinkSupplyC, ...
    supplyErrorC, ...
    pythonReturnC, ...
    simulinkReturnC, ...
    returnErrorC, ...
    simulinkLoadKw, ...
    simulinkCoolingKw, ...
    simulinkFlowHeatKw, ...
    'VariableNames', [ ...
        "time_s", ...
        "python_supply_temperature_c", ...
        "simulink_supply_temperature_c", ...
        "supply_error_c", ...
        "python_return_temperature_c", ...
        "simulink_return_temperature_c", ...
        "return_error_c", ...
        "simulink_heat_load_kw", ...
        "simulink_cooling_kw", ...
        "simulink_flow_heat_transfer_kw"]);

comparisonPath = fullfile(projectRoot, "results", "stage3b_comparison.csv");
writetable(comparison, comparisonPath);

figureHandle = figure("Visible", "off", "Color", "white", ...
    "Position", [100 100 1200 850]);
tiledlayout(2, 1, "TileSpacing", "compact", "Padding", "compact");

nexttile;
plot(timeS / 60, pythonSupplyC, "-", "LineWidth", 2.2, ...
    "Color", [0.09 0.41 0.67]);
hold on;
plot(timeS / 60, simulinkSupplyC, "o", "MarkerIndices", 1:12:numel(timeS), ...
    "MarkerSize", 4, "Color", [0.09 0.41 0.67]);
plot(timeS / 60, pythonReturnC, "-", "LineWidth", 2.2, ...
    "Color", [0.90 0.49 0.13]);
plot(timeS / 60, simulinkReturnC, "s", "MarkerIndices", 1:12:numel(timeS), ...
    "MarkerSize", 4, "Color", [0.90 0.49 0.13]);
xline(10, "--", "50 kW load step");
yline(7, "--", "CHWS setpoint");
grid on;
xlabel("Simulated time (minutes)");
ylabel("Temperature (deg C)");
title("Stage 3B Python-Simulink temperature comparison");
legend("Python CHWS", "Simulink CHWS", "Python CHWR", "Simulink CHWR", ...
    "Location", "southeast");

nexttile;
semilogy(timeS / 60, max(abs(supplyErrorC), eps), ...
    "LineWidth", 1.8, "Color", [0.09 0.41 0.67]);
hold on;
semilogy(timeS / 60, max(abs(returnErrorC), eps), ...
    "LineWidth", 1.8, "Color", [0.90 0.49 0.13]);
yline(acceptanceLimitC, "--", "Acceptance limit");
grid on;
xlabel("Simulated time (minutes)");
ylabel("Absolute difference (deg C)");
title("Independent trace comparison");
legend("CHWS difference", "CHWR difference", "Location", "southwest");

plotPath = fullfile(projectRoot, "docs", ...
    "stage3b-python-simulink-comparison.png");
exportgraphics(figureHandle, plotPath, "Resolution", 170);
close(figureHandle);

summary = table( ...
    maximumSupplyErrorC, ...
    maximumReturnErrorC, ...
    acceptanceLimitC, ...
    passed, ...
    simulinkSupplyC(end), ...
    simulinkReturnC(end), ...
    'VariableNames', [ ...
        "maximum_supply_error_c", ...
        "maximum_return_error_c", ...
        "acceptance_limit_c", ...
        "passed", ...
        "final_simulink_supply_c", ...
        "final_simulink_return_c"]);

summaryPath = fullfile(projectRoot, "results", "stage3b_summary.csv");
writetable(summary, summaryPath);

fprintf("Stage 3B Python-Simulink cross-validation\n");
fprintf("Samples compared: %d\n", numel(timeS));
fprintf("Maximum CHWS difference: %.3e deg C\n", maximumSupplyErrorC);
fprintf("Maximum CHWR difference: %.3e deg C\n", maximumReturnErrorC);
fprintf("Acceptance limit: %.1e deg C\n", acceptanceLimitC);
if passed
    validationResult = "PASS";
else
    validationResult = "FAIL";
end
fprintf("Cross-validation: %s\n", validationResult);
fprintf("Saved: %s\n", comparisonPath);
fprintf("Saved: %s\n", summaryPath);
fprintf("Saved: %s\n", plotPath);
end
